### ISSUE TITLE
Make sure you have set your working directory to wherever you have stored the CDRC-Retail-Catchment-Training folder we have provided:

### ISSUE THREAD

**Issue by w1806291** [patrickballantyne/CDRC-Retail-Catchment-Training#2]
Hi,

Where can I find this folder?

Thanks!

**Comment by patrickballantyne** [comment]
Hi James, 

We've just sent the folder off to the CDRC team for them to upload, so keep an eye out for it: https://data.cdrc.ac.uk/dataset/advanced-gis-methods-training-retail-centres-and-catchment-areas.

**Comment by nickbearman** [comment]
Data file now uploaded, listed on https://data.cdrc.ac.uk/dataset/advanced-gis-methods-training-retail-centres-and-catchment-areas. Any more questions, let us know!
